sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ewycheung/crwn-clothing -f Dockerfile.dev .

script:
  - docker run -e CI=true ewycheung/crwn-clothing yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "crwn-clothing"
  env: "Crwnclothing-env"
  bucket_name: "elasticbeanstalk-us-east-2-905144340828"
  bucket_path: "crwn-clothing"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
